# Objectives

## Study Objectives

::: {.instr_box .rmdnote}

Describe the purpose, specific aims, or objectives.

:::

The purpose of this study is to capture and describe the state of knowledge about how visual acuity, as measured by the Teller Acuity Card procedure, develops in children.
Our specific aims are as follows:

1. Survey the published literature on the use of Teller Acuity Cards (TAC) and capture the main effects found in that literature in an open database that will be shared with the research community for meta-analyses and related scholarship.</br>
2. Create and share openly a database of individual participant-level TAC data contributed by authors of published and unpublished research using the TAC. The combined data would eliminate all personally identifying information but would select, curate, organize and share other data about individual participant differences that may be useful for future research, such as participant ethnicity, sex/gender, clinical condition, geographic region (no smaller than county), etc. 

## Primary Study Endpoints

::: {.instr_box .rmdnote}

State the primary endpoints to be measured in the study.

Research typically has a primary objective or endpoint. 
Additional objectives and endpoints are secondary. 
The endpoints (or outcomes), determined for each study subject, are the quantitative measurements required by the objectives. 
Measuring the selected endpoints is the goal of a trial (examples: response rate and survival).

:::

The primary study endpoints are as follows:

1. The creation and publication of the study-level dataset.</br>
2. The creation and publication of the participant-level dataset.

## Secondary Study Endpoints

::: {.instr_box .rmdnote}

State the secondary endpoints to be measured in the study.

:::

Not applicable.
