# Background

## Scientific Background and Gaps

::: {.instr_box}

Describe the scientific background and gaps in current knowledge.
For clinical research studies being conducted at Penn State
Health/Penn State College of Medicine, and for other non-PSH locations
as applicable, describe the treatment/procedure that is considered
standard of care (i.e., indicate how patients would be treated in
non-investigational setting); and if applicable, indicate if the study
procedure is available to patient without taking part in the study.

:::
 
The Teller Acuity Card (TAC) procedure is a non-invasive technique for measuring a form of visual acuity in non-verbal participants, especially human infants and young children [@Teller1983-br].
The TAC is one of the most widely used measures of visual acuity.
A Google Scholar search[^2] for the term "teller acuity cards" on 2023-04-17 yielded more than 6,000 results.
And yet, to our knowledge, there is no single database of TAC results that is available to the research community.

[^2]: URL: <https://scholar.google.com/scholar?as_vis=1&q=teller+acuity+cards&hl=en&as_sdt=0,39>
 
## Previous Data

::: {.instr_box}

Describe any relevant preliminary data.

:::

Rick Gilmore has collected TAC data in his research on visual development in infants and children.
In looking through our records, we have found TAC data from some X children tested between X and X as part of a separate series of studies on motion perception.

## Study Rationale

::: {.instr_box}

Provide the scientific rationale for the research.

:::

The widespread use of a similar measurement across diverse populations represents a unique scientific opportunity to capture what is known about a fundamental property of human vision: How precisely can children see high contrast details at different ages?
