#	Study Design and Procedures

::: {.instr_box .rmdnote}

Data collection materials that will be seen or used by subjects in your study must be uploaded to CATS IRB (http://irb.psu.edu).   DO NOT include any actual data collection materials in this protocol (e.g., actual survey or interview questions)

:::

> [Do not type here]

## Study Design

::: {.instr_box .rmdnote}

Describe and explain the study design.

:::

> [Type protocol text here]


## Study Procedures

::: {.instr_box .rmdnote}

Provide a step by step description of all research procedures being conducted (broken down by visit, if applicable) including such information as below (where and when applicable); describe the following:
-	HOW: (e.g., data collection via interviews, focus groups, forms such as surveys and questionnaires, medical/school records, audio/video/digital recordings, photographs, EKG procedures, MRI, mobile devices such as electronic tablets/cell phones, observations, collection of specimens, experimental drug/device testing, manipulation of behavior/use of deception, computer games, etc.)
-	WHERE: (e.g., classrooms, labs, internet/online, places of business, medical settings, public spaces, etc.)

:::

### Phase 1: Literature search

1. Results of all papers matching the search term "Teller Acuity Cards" will be collected and stored in a Google Sheet: <https://docs.google.com/spreadsheets/d/1etFFmfE9e-Hjz7B19tFXT2NQKNV6RLuO1gFOCpGACEk/edit?usp=sharing>. Specifically, we will record the paper's title, authors, journal, abstract, and citation information.
2. The total number of research participants reported in the study will be recorded in the Google Sheet for each paper.
3. The age range (youngest age to oldest age) captured in the dataset will be recorded in the Google Sheet for each paper.
4. Developmental/clinical characteristics of the participants (e.g., typically developing, amblyopia, strabismus) will be recorded in the Google Sheet for each paper.

### Phase 2: Contacting researchers

1. The email address or addresses of the author(s) will be recorded in the Google Sheet.
2. Using Penn State's email server, an email will be sent to all author(s). See the specific text [here](include/txt/email-to-authors.txt).
3. An announcement will be sent via the Visionscience and Child Vision Research Society (CVRS) mailing lists seeking unpublished individual-level TAC datasets. See the specific text of that email [here](link/to/announcement-email.txt).

###	Visit 2 or Day 2 or Post-test, etc. (If applicable)

> [Type protocol text here]

##	Duration of Participation

> [Type protocol text here]
