# Future Undetermined Research: Data and Specimen Banking

::: {.instr_box}

If this study is collecting **identifiable** data and/or specimens
that will be banked for **future undetermined** **research**, please
describe this process in the sections below. This information should
not conflict with information provided in section 22 below OR the
"HRP-598 -- Research Data Plan Review Form" regarding whether or not
data and/or specimens will be associated with identifiers (directly or
indirectly). If there are no plans to use identifiable data/specimens
for future, undetermined research, then this section is **NOT
applicable**.

:::

> [Do not type here]

## Data and/or specimens being stored

::: {.instr_box}

Identify what data and/or specimens will be stored, and the data associated with each specimen.

:::

For the study-level dataset, data concerning age-, gender-, and  clinical-condition-related group acuity values (mean, standard deviation, median, inter-quartile range) will be stored along with publication-related data (journal, publication date, authors, aggregate sample sizes, etc.).

For the individual-level dataset, participant data concerning exact age at test, the year of the test (for future research on cohort effects), and the acuity score will be stored. Other individual-level data, if available, may also be stored, including ethnicity, gender, and clinical condition. Individual-level data will be linked to the researcher who provided it, and if appropriate, the published study with which the data are associated. 

## Location of storage

::: {.instr_box}

Identify the location where the data and/or specimens will be stored.

:::

During the project, data will be stored in Google Drive.


## Duration of storage

::: {.instr_box}

Identify how long the data and/or specimens will be stored. If data
and/or specimens will be stored indefinitely, indicate such.

:::

Data will be stored in Google Drive until the end of the project then transferred to a data repository for long-term storage.

## Access to data and/or specimens

::: {.instr_box}

Identify who will have access to the data and/or specimens.

:::


## Procedures to release data or specimens

::: {.instr_box}

Describe the procedures to release the data and/or specimens,
including: the process to request a release, approvals required for
release, who can obtain data and/or specimens, and the data to be
provided with the specimens.

:::

> [Type protocol text here or indicate as not applicable]


## Process for returning results

::: {.instr_box}

Describe the process for returning results about the use of the data
and/or specimens.

:::

> [Type protocol text here or indicate as not applicable]
