project:
  type: website
  render:
    - "*.qmd"
    - "irb/*.qmd"
  output-dir: "../docs"

book:
  title: "Legacy Project: Visual Acuity"
  author: "Rick Gilmore, Nicole Cruz, Julia DiFulvia, & Brianna Beamer"
  chapters:
    - href: index.qmd
    - href: about.qmd
    - part: "Protocol"
      chapters:
        - href: protocol_v01.qmd
    - part: "Data"
      chapters:
        - href: dashboard.qmd
        - href: data.qmd
        - href: data-management-plan.qmd
  repo-url: https://github.com/gilmore-lab/visual-acuity
  repo-actions: [edit, issue]
  repo-subdir: src

format:
  html:
    theme: cosmo
    css: include/css/styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    bibliography: [include/bib/teller-acuity-cards.bib]
    csl: include/bib/apa.csl
    date-modified: last-modified
editor: source
    