project:
  type: book
  render:
    - "*.qmd"
    - "irb/*.qmd"
  output-dir: "../docs"

book:
  title: "Legacy Project: Visual Acuity"
  author: 
    - "Rick Gilmore"
    - "Brianna Beamer"
    - "Nicole Cruz"
    - "Julia DiFulvio"
    - "Peter Huang"
    - "Andrea Seisler"
  chapters:
    - href: index.qmd
    - href: protocol_v01.qmd
      text: Protocol
    - href: dashboard.qmd
    - href: data.qmd
      text: "Cleaning & visualization"
    - part: "VSS 2025"
      chapters:
        - href: vss-2025-submission.qmd
        - href: vss-2025-poster.qmd
    - part: "Addenda"
      chapters:
        - href: data-management-plan.qmd
  repo-url: https://github.com/gilmore-lab/visual-acuity
  repo-actions: [edit, issue]
  repo-subdir: src

format:
  html:
    theme: cosmo
    css: include/css/styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    bibliography: [include/bib/teller-acuity-cards.bib]
    csl: include/bib/apa.csl
    date-modified: last-modified
    code-fold: true
    code-tools: true
    license: "CC BY"
editor: source
    