---
title: "dashboard"
format: html
params:
  data_dir: "data/csv"
  update_data: TRUE
  use_sysenv_creds: TRUE
  google_data_url: "https://docs.google.com/spreadsheets/d/1UFZkbh9oU4JHpYsrkDQcNmDyqD4J-qB74dhyMzIkqKs/edit?usp=sharing"
  sheet_name: "paper_data"
  data_fn: "paper-sources.csv"
---

This is a dashboard for the data collection and cleaning process.

## Set-up

```{r}
library(ggplot2)
```

## Download

```{r}
if (!dir.exists(params$data_dir)) {
  message("Creating missing ",  params$data_dir, ".")
  dir.create(params$data_dir)
}

if (params$update_data) {
  if (params$use_sysenv_creds) {
    google_creds <- Sys.getenv("GMAIL_SURVEY")
    if (google_creds != "") {
      options(gargle_oauth_email = google_creds)
      googledrive::drive_auth()
    } else {
      message("No Google account information stored in `.Renviron`.")
      message("Add authorized Google account name to `.Renviron` using `usethist::edit_r_environ()`.")
    }
  }

  papers_data <- googlesheets4::read_sheet(ss = params$google_data_url,
                            sheet = params$sheet_name)
  out_fn <- file.path(params$data_dir, params$data_fn)
  readr::write_csv(papers_data, out_fn)
  message("Data updated: ", out_fn)
} else {
  message("Using stored data.")
}
```

::: {.callout-note}

We have a separate tracking sheet that needs to be integrated into this workflow.

:::

## Clean

## Visualize

1. Time series of data collections by time.
2. Number of papers by pub date.

```{r}
#| title: "Papers by publication year"
#| fig-cap: "Papers by publication year"
papers_data |>
  ggplot() +
  aes(x = pub_year) +
  geom_bar()
```

3. By dates
4. Who entered

```{r}
#| title: "Papers entered by analyst"
#| fig-cap: "Papers entered by analyst"
papers_data |>
  ggplot() +
  aes(x = entered_by) +
  geom_bar()
```


5. Opened successfully
  - On PSU network
  
```{r}
#| title: "Papers with openable URLs"
#| fig-cap: "Papers with openable URLs"
papers_data |>
  ggplot() +
  aes(x = url_openable) +
  geom_bar()
```
  
  - Access via PSU Libraries
