---
title: Protocol
---

## Overview

This page describes the protocol for collecting, capturing, and cleaning data associated with the project.

The text here is adapted from a working draft document written in Google Docs that is hosted here:

<https://docs.google.com/document/d/1-ZKrNflBO7UIq5I0pJ8U5K-rtoiads12Zf_OQq_S65Q/edit>

## Literature search

### Goals

1. Capture the published literature that reports data on using Teller Acuity Cards.
2. Create a database of that literature.

### Phase I: Search

::: {.callout-note}

Here are some preparatory steps that need to be completed prior to doing literature search tasks.

1. Open Google Chrome from a lab computer.
2. Log into psubrainlab’s google account (psubrainlab@gmail.com ask Dr. Gilmore or Andrea for password)
2. Search “paperpile chrome extension” and install the paperpile chrome extension
3. On the paperpile website click ‘log in”. Choose the “log in with google” option

:::

#### Search terms

`teller acuity cards`
`visual acuity cards`
`teller cards`

#### Google Scholar

1. Visit Google Scholar: <https://scholar.google.com/>
2. Enter the search term
3. Make sure to select 'Sort by relevance', 'Any type', and *do not* check 'include patents' or 'include citations'

For example, this URL uses `teller acuity cards`:

<https://scholar.google.com/scholar?hl=en&as_sdt=0,39&as_vis=1&q=%22teller+acuity+cards%22>

When looking for sources on Google Scholar, look for the Paperpile box and ensure it is gray. Gray sources are sources we do not currently have in Paperpile. Green sources indicate we already have collected them in Paperpile. An example of both can be seen below.

INSERT FIGURES FROM GOOGLE DOC

4. After you have retrieved a page of entries, switch to the Paperpile tab to add the `TAC` tag to these entries. Use shift-click to select multiple entries in Paperpile.

::: {.callout-note}

It is possible to export the Paperpile references with the `TAC` tag directly to Github.
Rick tested this workflow on 2024-02-02.
What is yet unclear is whether the reference file automatically updates.

There appear to be some R packages that can read *.bib files and convert them to data frames, see <https://rdrr.io/cran/revtools/> and <https://docs.ropensci.org/bib2df/>.

:::

### Phase II: Data entry

### Contacting authors

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdp6HK0FldL5awoT8LTXnr8Sqe7QbDxGc-gjhOpVJ452GLlqA/viewform?embedded=true" width="640" height="1370" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

## Literature evaluation

### Goals

1. To evaluate which of the papers captured in the literature search have group or individual level data that can be extracted.

### Evaluation

## Data extraction

### Goals

1. To extract group-level data from each paper identified in the prior phase.
2. Enter group-level data into a common database.

### Data extraction

### Qualty Assurance


